site_name: DLang Documentation
site_description: A data-oriented systems programming language (working name)
site_url: https://deablofk.github.io/dlang-docs/
docs_dir: docs
site_dir: site
use_directory_urls: false

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pt
          name: Português
          build: true
